spring.application.name=bluememo

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Database URL (replace 'localhost:5432/your_database_name' with your details)
spring.datasource.url=jdbc:postgresql://localhost:5432/bluememo_db

# Database Credentials
spring.datasource.username=app_user
spring.datasource.password=user

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update