spring.application.name=bluememo

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Database URL (replace 'localhost:5432/your_database_name' with your details)
spring.datasource.url=jdbc:postgresql://database:5432/${POSTGRES_DB}

# Database Credentials
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

bluememo.jwt.secret=${JWT_SECRET}
bluememo.jwt.expiration-ms=900000