spring.application.name=bluememo

server.port=${SERVER_PORT:8080}

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

bluememo.jwt.secret=${JWT_SECRET}
bluememo.jwt.expiration-ms=${JWT_EXPIRATION_MS:900000}